{% set name = "banana-hep" %}
{% set version = "0.6.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0cf4a78f5affa5e1afe138ae6c9df5414deb9785901b585fcbdf6bbf531a1b9b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.12
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - appdirs >=1.4.4,<2.0.0
    - click >=8.0.3,<9.0.0
    - ipython >=8.1.0,<9.0.0
    - matplotlib-base >=3.5.1,<4.0.0
    - numpy >=1.21.0,<2.0.0
    - pandas >=1.3.5,<2.0.0
    - pendulum >=2.1.2,<3.0.0
    - python >=3.8,<3.12
    - pyyaml =6.0
    - rich >=12.4.4,<13.0.0
    - sqlalchemy >=1.4.29,<2.0.0

test:
  imports:
    - banana
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://banana-hep.readthedocs.io
  dev_url: https://github.com/N3PDF/banana
  summary: Benchmarking infrastructure for Deep Inelastic Scattering and evolution codes used in High Energy Physics.
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scarlehoff
