schema_version: 1

context:
  name: banana-hep
  version: 0.6.15

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/banana_hep-${{ version }}.tar.gz
  sha256: 96069215af1d56f76d80e428c679d399b30ceb357875d29b583706826e144e45

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=${{ python_min }},<3.13
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }},<3.13
    - ipython >=8.1.0,<9.0.0
    - sqlalchemy >=1.4.29,<2.0.0
    - numpy >=1.26.0,<2.0.0
    - pandas >=2.1.4,<3.0.0
    - matplotlib-base >=3.5.1,<4.0.0
    - rich >=12.4.4,<13.0.0
    - pyyaml >=6.0.0,<7.0.0
    - click >=8.0.3,<9.0.0
    - pendulum >=3.0.0,<4.0.0
    - appdirs >=1.4.4,<2.0.0

tests:
  - python:
      imports:
        - banana
      pip_check: true

about:
  summary: Benchmarking infrastructure for Deep Inelastic Scattering and evolution codes used in High Energy Physics.
  license: GPL-3.0-only
  license_file: LICENSE
  homepage: https://banana-hep.readthedocs.io
  repository: https://github.com/N3PDF/banana

extra:
  recipe-maintainers:
    - scarlehoff
